# Generated by Django 4.1.4 on 2023-03-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkmembers',
            options={},
        ),
        migrations.RemoveField(
            model_name='networkmembers',
            name='created_on',
        ),
    ]
