# Generated by Django 4.1.4 on 2023-03-28 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventnet', '0002_alter_meep_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meep',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meepnetwork', to='ventnet.networks'),
        ),
    ]
