# Generated by Django 4.1.7 on 2023-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventnet', '0003_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='meep',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meep',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meep',
            name='body',
            field=models.CharField(default='', max_length=400),
        ),
    ]
